sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t japostolidis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true japostolidis/docker-react npm run test